### ISSUE TITLE
createReadStream is not a function

### ISSUE THREAD

**Issue by taikishiino** [meabed/graphql-upload-ts#108]
Hi👋

I am trying to develop a file upload function on an API server built with Nest.js, GraphQL, TypeScript.

The multipart request was successfully communicated, but when I use `createReadStream()` in the server side logic, I am getting the error message.
Do you know the cause?

## Verification Codes
```ts
// main.ts
import { NestFactory } from '@nestjs/core'
import { ValidationPipe } from '@nestjs/common'
import { AppModule } from './app.module'
import { graphqlUploadExpress } from 'graphql-upload-ts'

async function bootstrap() {
  const app = await NestFactory.create(AppModule)

  app.useGlobalPipes(new ValidationPipe())
  app.use(graphqlUploadExpress({ maxFileSize: 1000000, maxFiles: 10 }))

  await app.listen(8080, '0.0.0.0')
}
bootstrap()
```

```ts
// app.resolver.ts
import { Resolver, InputType, Field, Args, Mutation } from '@nestjs/graphql'
import { FileUpload, GraphQLUpload } from 'graphql-upload-ts'

@InputType()
export class UploadImageInput {
  @Field(() => GraphQLUpload)
  imageFile!: Promise<FileUpload>
}

@Resolver()
export class AppResolver {
  constructor(){}

  @Mutation(() => Boolean, { name: 'uploadImage' })
  async uploadImage(@Args('input') { imageFile }: UploadImageInput) {
    console.log(imageFile)
    const { createReadStream, filename } = await imageFile
    console.log('filename --->>', filename)
    console.log('createReadStream --->>', createReadStream)
    const stream = createReadStream()
    console.log(stream)
    return true
  }
}
```

<details>
<summary>console.log</summary>

```
Promise {
  {
    fieldName: '1',
    filename: 'Polygon 2.png',
    mimetype: 'image/png',
    encoding: '7bit',
    createReadStream: {
      _readableState: [Object],
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      truncated: false,
      _readcb: null
    }
  }
}
filename --->> Polygon 2.png
createReadStream --->> {
  _readableState: {
    objectMode: false,
    highWaterMark: 16384,
    buffer: { head: [Object], tail: [Object], length: 1 },
    length: 1544,
    pipes: [],
    flowing: null,
    ended: true,
    endEmitted: false,
    reading: false,
    constructed: true,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    dataEmitted: false,
    decoder: null,
    encoding: null
  },
  _events: { end: undefined, limit: undefined, error: undefined },
  _eventsCount: 2,
  _maxListeners: undefined,
  truncated: false,
  _readcb: null
}
[Nest] 36747  - 2023/02/04 18:09:09   ERROR [ExceptionsHandler] createReadStream is not a function
TypeError: createReadStream is not a function
```

</details>

## environment
- "graphql-upload-ts": "^2.0.5"
- "graphql": "^16.6.0"
- "@nestjs/core": "^9.3.2"
- "@nestjs/common": "^9.3.2"
- "@nestjs/graphql": "^10.1.7"
- "class-validator": "0.13.2"
- .node-version: 18.11.0

**Comment by meabed** [comment]
Thank you for posting this,
Would you be able to put this in codesandbox so I could easily check and fix it.

**Comment by taikishiino** [comment]
@meabed 
I put it in this codesandbox
https://codesandbox.io/p/sandbox/nest-graphql-upload-ts-forked-965o7d?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A2%7D%5D&file=%2FREADME.md

In order to confirm reproduction of the error, it is recommended that you clone this repository locally.
https://github.com/taikishiino/nest-graphql-upload-ts
(since you will need to send a request from the front end to the API server you started at `http://127.0.0.1:8080/graphql`)

**Comment by meabed** [comment]
Thanks @taikishiino I have checked and the issue seems to from nestjs ValidatePipe, you need to enable `transform: true` to have access to the createReadStream after nestjs serilize the request for validation

https://docs.nestjs.com/techniques/validation#transform-payload-objects


```
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
  }))


```

**Comment by senorscan** [comment]
@meabed I am having the opposite issue. When i add `transform: true` it doesn't work and i get the `createReadStream is not a function` error. Any ideas on how we can have the tranform globably true and for it work with graphql-upload-ts?

**Comment by meabed** [comment]
@senorscan would you able to share code sandbox?

**Comment by senorscan** [comment]
I sorted it! I am working on a NestJs v 10 app and was having issues. I updated some of the dependencies and now it seems to be fine.
