### ISSUE TITLE
graphql-upload-ts does not allow calling createReadStream() multiple times

### ISSUE THREAD

**Issue by senorgeno** [meabed/graphql-upload-ts#198]
Hi there, 

I am getting the below error in production occasionally. I cannot for the life of me replicate it. Do you have any ideas?

Much appreciated!

```graphql-upload-ts does not allow calling createReadStream() multiple times. Please, consume the previously returned stream. Make sure you're not referencing same file twice in your...```

**Comment by meabed** [comment]
Maybe related https://github.com/meabed/graphql-upload-ts/issues/108#issuecomment-1419022570

Also please share codesandbox to reproduce if the problem still exist or the fix so others could find it :)

**Comment by senorgeno** [comment]
Hmm not sure it's that. I did have that problem as you can see I commented further down albeit with a different github user (senorscan) and was able to fix that. 

The tricky thing about this issue is I can't replicate it. It's only happening in production! I might swap to `graphql-upload` and see if the issue still persists.

**Comment by meabed** [comment]
@senorgeno I have tested with files larger than 20mb and it works fine. 

Could you share reproducible code and file for this issue?

```
{
  "data": {
    "uploadFile": {
      "uri": "/Users/meabed/workspace/graphql-upload-ts/examples/apollo/dist/examples/apollo/uploaded-1705325159941-2.pdf",
      "filename": "2.pdf",
      "mimetype": "application/pdf",
      "encoding": "7bit",
      "fileSize": 26676280
    }
  }
}
```

<img width="1667" alt="image" src="https://github.com/meabed/graphql-upload-ts/assets/45731/01c301d0-2d39-4280-94da-41b9fdd27835">

Could you have a look at the demo and try to reproduce the issue and submit the codebase you had this issue with?
