### ISSUE TITLE
Nestjs Server Crashes sometimes when upload fails

### ISSUE THREAD

**Issue by Usama-Tahir** [meabed/graphql-upload-ts#202]
Hey, I am using `graphql-upload-ts` with Nest.js. This works great but this crashes the Nestjs server when upload fails.  On analyzing the logs, I got this `"BadRequestError: Request disconnected during file upload stream parsing." `. I was unable to reproduce it so it mimic it, I added the following line [here](https://github.com/meabed/graphql-upload-ts/blob/master/src/processRequest.ts#L273)

```
return exit(`Dummy Error Message`);
```

This resulted in crashing the server.

I also observed that in this case, no catch block was called.

```
    processRequest(request, response, processRequestOptions)
      .then((body: any) => {
        request.body = body;
        next();
      })
      .catch((error: any) => {
        if (error.status && error.expose) response.status(error.status);
        next(error);
      });
```

I also tried to pass the `next` to `processRequest` and call it from the `exit` function but that also didn't work.

It looks like a promise rejection is not appropriately handled somewhere, but I can't figure it out.

Ideally, It shouldn't crash the Nest.js server and only cancel the request.

**Comment by meabed** [comment]
@Usama-Tahir I have tested with files larger than 20mb and it works fine. 

Could you share reproducible code and file for this issue?

```
{
  "data": {
    "uploadFile": {
      "uri": "/Users/meabed/workspace/graphql-upload-ts/examples/apollo/dist/examples/apollo/uploaded-1705325159941-2.pdf",
      "filename": "2.pdf",
      "mimetype": "application/pdf",
      "encoding": "7bit",
      "fileSize": 26676280
    }
  }
}
```

<img width="1667" alt="image" src="https://github.com/meabed/graphql-upload-ts/assets/45731/01c301d0-2d39-4280-94da-41b9fdd27835">

Could you have a look at the demo and try to reproduce the issue and submit the codebase you had this issue with?
